name: Python Code Quality

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [impalaai, runner, impala-utils]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Run black for ${{ matrix.project }}
        id: black
        working-directory: ${{ matrix.project }}
        run: |
          black --check --diff .

      - name: Run isort for ${{ matrix.project }}
        id: isort
        working-directory: ${{ matrix.project }}
        run: |
          isort --check-only --diff .
