name: Unit Tests

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ./impala-utils
        pip install "./impalaai[dev]"
    
    - name: Run unit tests
      run: |
        cd impalaai
        python -m pytest tests/unit/ -v --tb=short --color=yes